{{ if .Values.terraform.enabled }}
apiVersion: terraformcontroller.cattle.io/v1
kind: Module
metadata:
  name: tf-module
  namespace: {{ .Release.Namespace }}
spec:
  git:
    url: {{ (index $.Values.terraform $.Values.terraform.provider).module_repo }}
{{ end }}