apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.certmanager.certificateName }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.certmanager.secretName }}
  dnsNames:
  - "auth-service.{{ .Release.Namespace }}.svc.cluster.local"
  - "auth-service.{{ .Release.Namespace }}.svc"
  - "auth-service.{{ .Release.Namespace }}"
  issuerRef:
    name: {{ .Values.certmanager.issuerName }}