apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gargantua-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["hobbyfarm.io", "terraformcontroller.cattle.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gargantua-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: default
roleRef:
  kind: ClusterRole
  name: gargantua-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gargantua
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gargantua
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: default
roleRef:
  kind: Role
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io