apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: auth-service
  template:
    metadata:
      labels:
        component: auth-service
    spec:
      containers:
        - name: auth-service
          image: {{ $.Values.auth.image }}
          command: ["authservice"]
          args:
          - "-v=9"
          - "-logtostderr"
          env:
            - name: LOG_LEVEL
              value: {{ $.Values.auth.logLevel | quote }}
            - name: HF_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: PORT
              value: {{ .Values.auth.apiPort | quote }}
            - name: GRPC_PORT
              value: {{ .Values.auth.grpcPort | quote }}
          ports:
          - containerPort: {{ .Values.auth.apiPort }}
          - containerPort: {{ .Values.auth.grpcPort }}
          volumeMounts:
          - name: auth-secret
            mountPath: "/etc/ssl/certs/ca.crt"
            subPath: ca.crt
            readOnly: true
          - name: auth-secret
            mountPath: "/etc/ssl/certs/tls.key"
            subPath: tls.key
            readOnly: true
          - name: auth-secret
            mountPath: "/etc/ssl/certs/tls.crt"
            subPath: tls.crt
            readOnly: true
      volumes:
      - name: auth-secret
        secret:
          secretName: hobbyfarm-auth-secret
          optional: false