apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ $.Values.auth.replicas }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: {{ $.Values.auth.image }}
        command:
        - authservice
        env:
          - name: HF_NAMESPACE
            value: {{ .Release.Namespace }}