apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: auth-service
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
      targetPort: 80