apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: auth-service
  ports:
  - name: http
    port: 80
  - name: grpc
    protocol: TCP
    port: 8080
    targetPort: 8080
