apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: webhook-authn
spec:
  selector:
    component: auth-service
  ports:
  - name: webhook
    port: {{ .Values.auth.webhook.servicePort }}
    targetPort: {{ .Values.auth.webhook.containerPort }}