apiVersion: v1
kind: ConfigMap
metadata:
  namespace: hobbyfarm
  name: ui-config
data:
  config.json: |
    {
        "title": {{ $.Values.ui.config.title | quote }},
        "favicon": {{ $.Values.ui.config.favicon | quote }},
        "login": {
            "logo": {{ $.Values.ui.config.login.logo | quote }},
            "background": {{ $.Values.ui.config.login.background | quote }}
        },
        "logo": {{ $.Values.ui.config.logo | quote }}
    }
  custom.css: {{ $.Values.ui.custom | quote }}