apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: ui
  template:
    metadata:
      labels:
        component: ui
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: ui
          image: {{ $.Values.ui.image }}
          {{ if $.Values.insecure }}
          args:
            - --insecure
          {{ end -}}
          env:
            - name: HF_SERVER
              {{ if $.Values.ingress.enabled }}
              value: {{ $.Values.ingress.hostnames.backend | quote }}
              {{ else }}
              value: gargantua
              {{ end }}
      {{- if $.Values.ui.configMapName }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
            - name: config
              mountPath: /usr/share/nginx/html/custom.css
              subPath: custom.css
      volumes:
        - name: config
          configMap: 
            name: {{ $.Values.ui.configMapName }}
      {{- end }}
