apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
  namespace: kube-system
data:
  webhook-config.yaml: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: example-cluster
        cluster:
          server: http://localhost:3000/authenticate
        contexts:
          - context:
              cluster: example-cluster
              user: example-user
            name: default-context
        current-context: default-context
        users:
          - name: example-user
            user:
              token: secret
