{{ if $.Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
  - host: {{ $.Values.ingress.hostnames.gateway }}
    http:
      paths:
      - pathType: Prefix
        path: "/auth"
        backend:
          service:
            name: authn-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/a/user"
        backend:
          service:
            name: user-service
            port: 
              number: 80
{{ if $.Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ $.Values.ingress.hostnames.gateway }}
{{- if hasKey .Values.ingress.tls.secrets "gateway" }}
    secretName: {{ $.Values.ingress.tls.secrets.gateway }}
{{- end }}
{{ end }}
{{ end }}