# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: conversion-{{ .Release.Namespace }}
# rules:
#   - apiGroups: ["admissionregistration.k8s.io"]
#     resources: ["*"]
#     verbs: ["*"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: conversion-{{ .Release.Namespace }}
# subjects:
#   - kind: ServiceAccount
#     namespace: {{ .Release.Namespace }}
#     name: {{ .Values.conversion.serviceAccountName }}
# roleRef:
#   kind: ClusterRole
#   name: conversion-{{ .Release.Namespace }}
#   apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: conversion
rules:
  - apiGroups: ["hobbyfarm.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conversion
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.conversion.serviceAccountName }}
roleRef:
  kind: Role
  name: conversion
  apiGroup: rbac.authorization.k8s.io