apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: hobbyfarm-webhook
spec:
  selector:
    component: user-service
  ports:
  - name: webhook
    port: {{ .Values.user.webhook.servicePort }}
    targetPort: {{ .Values.user.webhook.containerPort }}