apiVersion: v1
kind: Service
metadata:
  name: guac
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    component: guac
  ports:
    - name: http
      port: 4567
      nodeport: 30008