apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: hobbyfarm-webhook
spec:
  selector:
    component: gargantua
  ports:
  - name: webhook
    port: {{ .Values.gargantua.webhook.servicePort }}
    targetPort: {{ .Values.gargantua.webhook.containerPort }}