name: Publish

on:
  push:
    branches:
      - master
    paths:
      - '**/Chart.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: check if version was bumped
      run: git diff HEAD~1 charts/hobbyfarm/Chart.yaml | grep 'version:'
    - name: debug .git directory
      run: |
        ls -la $PWD/.git
    - name: package and release charts
      env:
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
        CR_TOKEN: ${{ secrets.CR_TOKEN }}
      run: |
        docker run -v $PWD:/app -v $PWD/.git:/app/.git quay.io/helmpack/chart-releaser:v1.6.1 package /app/charts/hobbyfarm --package-path /app/.cr-release-packages
        docker run -v $PWD:/app -v $PWD/.git:/app/.git quay.io/helmpack/chart-releaser:v1.6.1 upload --owner $OWNER --git-repo $REPO --package-path /app/.cr-release-packages --token $CR_TOKEN
        docker run -v $PWD:/app -v $PWD/.git:/app/.git --workdir /app quay.io/helmpack/chart-releaser:v1.6.1 index  --owner $OWNER --git-repo $REPO --package-path /app/.cr-release-packages --index-path /app/docs/index.yaml
    - name: commit updated index.yaml
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "update index.yaml" -a
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
